--For latest version check MWBFile
-- MySQL Script generated by MySQL Workbench
-- 06/24/16 18:41:32
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema awstimesheet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `awstimesheet` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `awstimesheet` ;

-- -----------------------------------------------------
-- Table `awstimesheet`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstimesheet`.`resource` (
  `resource_id` INT NOT NULL AUTO_INCREMENT,
  `resource_name` VARCHAR(45) NULL,
  `adminLevel` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`resource_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstimesheet`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstimesheet`.`project` (
  `project_id` INT NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `project_name_UNIQUE` (`project_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstimesheet`.`project_timesheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstimesheet`.`project_timesheet` (
  `project_timesheet_id` INT NOT NULL AUTO_INCREMENT,
  `resource_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  INDEX `fk_project_timesheet_resource1_idx` (`resource_id` ASC),
  INDEX `fk_project_timesheet_project1_idx` (`project_id` ASC),
  UNIQUE INDEX `project_timesheet_id_UNIQUE` (`project_timesheet_id` ASC),
  PRIMARY KEY (`resource_id`, `project_id`),
  CONSTRAINT `fk_project_timesheet_resource1`
    FOREIGN KEY (`resource_id`)
    REFERENCES `awstimesheet`.`resource` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_timesheet_project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `awstimesheet`.`project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstimesheet`.`time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstimesheet`.`time` (
  `date` DATE NOT NULL,
  `timelogged` DOUBLE NULL DEFAULT 0.0,
  `project_timesheet_id` INT NOT NULL,
  `notes` VARCHAR(2000) NULL,
  PRIMARY KEY (`date`, `project_timesheet_id`),
  INDEX `fk_time_project_timesheet1_idx` (`project_timesheet_id` ASC),
  CONSTRAINT `fk_time_project_timesheet1`
    FOREIGN KEY (`project_timesheet_id`)
    REFERENCES `awstimesheet`.`project_timesheet` (`project_timesheet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `awstimesheet`.`funFact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `awstimesheet`.`funFact` (
  `idfunFact` INT NOT NULL AUTO_INCREMENT,
  `funFact` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`idfunFact`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
